import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Matthew Haines - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Matthew Haines</h1>I am a versatile Full Stack Software Engineer with
      a background in Graphic Design and Audio. My entrepreneurial ventures,
      particularly in client-facing businesses, have cultivated my creative
      problem-solving skills. I am eager to contribute my unique skill set to
      drive innovation and success within your software engineering team.
    </>
  );
}
